apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtuasoc.fullname" . }}-config
  labels:
    {{- include "virtuasoc.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  API_BASE_PATH: {{ .Values.env.apiBasePath | quote }}
  AUTH_MODE: {{ .Values.env.authMode | quote }}
  DISTRIBUTION_REQUIRE_APPROVAL: {{ .Values.env.distributionRequireApproval | quote }}
  REDACT_PII_ON_DISTRIBUTION: {{ .Values.env.redactPiiOnDistribution | quote }}
  DATA_RETENTION_DAYS: {{ .Values.env.dataRetentionDays | quote }}
  FEATURE_FACTORY_APP: {{ .Values.env.featureFactoryApp | quote }}


