apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtuasoc.fullname" . }}-worker
  labels:
    {{- include "virtuasoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "virtuasoc.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ include "virtuasoc.fullname" . }}-config
            - secretRef:
                name: {{ include "virtuasoc.secretName" . }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}


