apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtuasoc.fullname" . }}-worker
  labels:
    {{- include "virtuasoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "virtuasoc.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "virtuasoc.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.gcp.cloudSqlProxy.enabled }}
        - name: cloud-sql-proxy
          image: {{ .Values.gcp.cloudSqlProxy.image | quote }}
          args:
            {{- if .Values.gcp.cloudSqlProxy.privateIp }}
            - "--private-ip"
            {{- end }}
            - "--port={{ .Values.gcp.cloudSqlProxy.port }}"
            - {{ .Values.gcp.cloudSqlProxy.instanceConnectionName | quote }}
        {{- end }}
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: {{ include "virtuasoc.fullname" . }}-config
            - secretRef:
                name: {{ include "virtuasoc.secretName" . }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}


