apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtuasoc.fullname" . }}-api
  labels:
    {{- include "virtuasoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http


