apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtuasoc.fullname" . }}-web
  labels:
    {{- include "virtuasoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: http


